language: node_js
node_js:
  - "10"

branches:
  except:
    - gh-pages # will be deployed to, no need to build it

install:
  - npm install

script:
  - npm run lint
  - ng build --prod --base-href /
  - mv dist/SENA/index.html dist/SENA/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/SENA
  fqdn: sena.kiondc.io
  on:
    branch: master
